### PR TITLE
Updates to GPCR Tutorial

### PR DESCRIPTION
**Pull request by HEJ845**
Commands edited for Linux, additional instructions added for installing dssp, links to tutorial files added, some file names corrected.

### CODE REVIEW

**Comment by jkalayan** [comment]
Changes look great @HEJ845, looks like one of the .rst is causing pre-commit to fail. You can run pre-commit to fix this and then resubmit your PR.

You might need to run `pre-commit install` so it installs the hooks, then you can run `pre-commit run --all-files` to conform to pre-commit formatting rules.

**Comment by HEJ845** [comment]
@jkalayan Great! And apologies for that, let me fix it and I'll resubmit.

**Comment by jkalayan** [comment]
Thanks @HEJ845, looks much more user friendly and easier to read with your changes in separating out some of the `sed` steps. PR has been merged :)

**Comment by HEJ845** [comment]
Very much my pleasure @jkalayan, really glad you like the look of it! Thanks for your help with it all.

**Pull request closed without merging**
